version: "3"
services:
  jmix-bookstore:
    container_name: jmix-bookstore-app
    image: jmix/jmix-bookstore
    depends_on:
      - postgres
    environment:
      - MAIN_DATASOURCE_URL=jdbc:postgresql://postgres/bookstore
      - BOOKSTORE_LOCATIONIQ_API_KEY=${BOOKSTORE_LOCATIONIQ_API_KEY}
    ports:
      - "8080:8080"
  postgres:
    container_name: jmix-bookstore-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bookstore
