name: CI pipeline

on:
  push:
    branches:
      - main
      - test
  pull_request:

jobs:
  ci:
    name: CI pipeline
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

#      - name: Run tests
#        env:
#          PREMIUM_REPO_USER: ${{ secrets.PREMIUM_REPO_USER }}
#          PREMIUM_REPO_PASS: ${{ secrets.PREMIUM_REPO_PASS }}
#        run: ./gradlew test
#
#      - name: Publish Test Report
#        uses: mikepenz/action-junit-report@v3
#        if: always() # always run even if the previous step fails
#        with:
#          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Build JAR
        env:
          PREMIUM_REPO_USER: ${{ secrets.PREMIUM_REPO_USER }}
          PREMIUM_REPO_PASS: ${{ secrets.PREMIUM_REPO_PASS }}
        run: ./gradlew -Pvaadin.productionMode=true bootJar

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jmix/jmix-bookstore:test
